palette = "cyberdream"
# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true

# Move the directory to the second line
format = "$all"

[kubernetes]
disabled = false
symbol = '⎈ '
format = '[$symbol](bold blue)[$context](magenta)[( \($namespace\))](yellow) in '

[direnv]
disabled = false

[os]
disabled = false

[os.symbols]
Macos = " " 

[palettes.cyberdream]
blue = "#5ea1ff"
green = "#5eff6c"
cyan = "#5ef1ff"
red = "#ff6e5e"
yellow = "#f1ff5e"
magenta = "#ff5ef1"
pink = "#ff5ea0"
orange = "#ffbd5e"
purple = "#bd5eff"
